\n\n-- Create dashboard_stats table\nCREATE TABLE IF NOT EXISTS dashboard_stats (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  metric_name text NOT NULL,\n  value numeric NOT NULL DEFAULT 0,\n  previous_value numeric NOT NULL DEFAULT 0,\n  period text NOT NULL,\n  updated_at timestamptz DEFAULT now()\n)
\n\n-- Create dashboard_charts table\nCREATE TABLE IF NOT EXISTS dashboard_charts (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  chart_type text NOT NULL,\n  title text NOT NULL,\n  data jsonb NOT NULL DEFAULT '[]'::jsonb,\n  updated_at timestamptz DEFAULT now()\n)
\n\n-- Enable RLS\nALTER TABLE dashboard_stats ENABLE ROW LEVEL SECURITY
\nALTER TABLE dashboard_charts ENABLE ROW LEVEL SECURITY
\n\n-- Create policies for dashboard_stats\nCREATE POLICY "Dashboard stats are viewable by authenticated users"\n  ON dashboard_stats\n  FOR SELECT\n  TO authenticated\n  USING (true)
\n\nCREATE POLICY "Dashboard stats are modifiable by admin users"\n  ON dashboard_stats\n  FOR ALL\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM users\n      WHERE users.id = auth.uid()\n      AND users.role = 'admin'\n    )\n  )
\n\n-- Create policies for dashboard_charts\nCREATE POLICY "Dashboard charts are viewable by authenticated users"\n  ON dashboard_charts\n  FOR SELECT\n  TO authenticated\n  USING (true)
\n\nCREATE POLICY "Dashboard charts are modifiable by admin users"\n  ON dashboard_charts\n  FOR ALL\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM users\n      WHERE users.id = auth.uid()\n      AND users.role = 'admin'\n    )\n  )
\n\n-- Insert initial dashboard stats\nINSERT INTO dashboard_stats (metric_name, value, previous_value, period) VALUES\n  ('total_users', 1274, 1062, 'monthly'),\n  ('active_products', 845, 735, 'monthly'),\n  ('revenue', 45231, 36185, 'monthly'),\n  ('active_sessions', 573, 512, 'monthly')\nON CONFLICT DO NOTHING
\n\n-- Insert initial chart data\nINSERT INTO dashboard_charts (chart_type, title, data) VALUES\n  (\n    'line',\n    'Продажи по месяцам',\n    '[\n      {"name": "Янв", "value": 2400},\n      {"name": "Фев", "value": 1398},\n      {"name": "Мар", "value": 9800},\n      {"name": "Апр", "value": 3908},\n      {"name": "Май", "value": 4800},\n      {"name": "Июн", "value": 3800}\n    ]'::jsonb\n  ),\n  (\n    'pie',\n    'Распределение продуктов',\n    '[\n      {"name": "Группа A", "value": 400},\n      {"name": "Группа B", "value": 300},\n      {"name": "Группа C", "value": 300},\n      {"name": "Группа D", "value": 200}\n    ]'::jsonb\n  ),\n  (\n    'bar',\n    'Активность пользователей',\n    '[\n      {"name": "Пн", "value": 40},\n      {"name": "Вт", "value": 30},\n      {"name": "Ср", "value": 20},\n      {"name": "Чт", "value": 27},\n      {"name": "Пт", "value": 18},\n      {"name": "Сб", "value": 23},\n      {"name": "Вс", "value": 34}\n    ]'::jsonb\n  )\nON CONFLICT DO NOTHING
